a = [1, 2]
b = [3, 4]
print(a, b)
print(*a, *b)
ab = list(a)
ab.extend(b)
print(ab)
aab = list(a)
aab.append(b)
print(aab)
print(ab.count(2))
print(ab+aab)
range_set = list(range(2, 20, 2))
print(range_set)
print(range_set[1:6:2])
print(range_set[::-1])
range_args = (-20, 21, 5)
range_set1 = list(range(*range_args))
print(range_args)
print(*range_args, sep=",")
print(range_set1)
dict_zipped = dict(zip(ab, range_set))
print(dict_zipped)
